# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dca62a37e4c6a1c08a0595f47491178ee79a224a752a7459e06aa88191573d65b62ea128761cc452fa1943da6195dbf1e9416e6d88a707a453a6db5449b82178

test:
  secret_key_base: 67541b82dc6849ee7b13d9a8afca4deabdf70d5cc7e0cac07d40cdd3c7067af94f35217eac06737c55894835e5f130839c2c3858b3f9d04c5e4196e5f076528f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
